// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mark_vnil._1.Data;

#nullable disable

namespace mark_vnil._1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705202325_IndexAddedOnROVDetectedItemLabel")]
    partial class IndexAddedOnROVDetectedItemLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("mark_vnil._1.Models.ROVDetectedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAtTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotFileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Label");

                    b.HasIndex("StreamId");

                    b.ToTable("ROVDetectedItems");
                });

            modelBuilder.Entity("mark_vnil._1.Models.ROVStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ROVStreams");
                });

            modelBuilder.Entity("mark_vnil._1.Models.ROVDetectedItem", b =>
                {
                    b.HasOne("mark_vnil._1.Models.ROVStream", "Stream")
                        .WithMany("ROVDetectedItems")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("mark_vnil._1.Models.ROVStream", b =>
                {
                    b.Navigation("ROVDetectedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
